### ISSUE TITLE
Unable to detect window on dual monitor setup

### ISSUE THREAD

**Issue by DariusSohWX** [SamTheCoder777/E7-RTA-Helper#4]
It is unable to detect bluestacks despite running as admin. If relevant, I have a dual monitor set up.

**Comment by SamTheCoder777** [comment]
It is probably dual monitor messing up screenshot script. I didn't really test it with dual monitor because I only have a laptop with single screen right now.

When you say it is unable to detect, do you mean the title of the window doesn't show up in the `Set Detection Screen Size` on the title drop down menu 

or

you can select your game title on the drop down menu but it says error along the lines of "Unable to capture the window"

**Comment by DariusSohWX** [comment]
the title of the window does not show up at all, only 'window' was available to select. when selected and set, it just shows white screen.

**Comment by SamTheCoder777** [comment]
I couldn't reproduce the bug with a virtual monitor, Ill try to find someone that has a physical dual monitor set up to help me reproduce the issue.

**Comment by DariusSohWX** [comment]
Well, it seems to work now. Restarting my pc might have fixed it, not sure what the initial problem was that caused the issue. Thanks for your time!
